version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: todo_app
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/log:/var/log/mysql

  api:
    image: golang:latest
    container_name: api
    ports:
      - "8080:8080"
    command: go run cmd/main.go
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./api:/app/api
    working_dir: /app/api
    stdin_open: true

  views:
    image: node:latest
    container_name: views
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db
    volumes:
      - ./views:/app/views
    working_dir: /app/views
    stdin_open: true
