openapi: '3.0.2'

info:
  title: "ToDoApp"
  description: "todoアプリのAPIドキュメント"
  version: '1.0'
servers:
  - url: "https://localhost:8000"
    description: "ローカル"
    
paths:
  /tasks:
    get:
      summary: task一覧を取得
      description: tasksテーブルからtitle, is_completed, deadlineを取得する。
      operationId: GetTaskList
      tags:
        - todo一覧
      deprecated: false
      responses:
        200:
          description: データを取得しました

  /tasks/{taskId}:
    get:
      summary: "taskの詳細を取得"
      description: "tasksテーブルから個別のtaskを取得する。取得するカラムはtitle, content, is_completed, deadline"
      tags:
        - "todo詳細"
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
          description: tasksテーブルのid
      deprecated: false
      security:
        - api_key: []
      responses:
        '200':
          description: OK


