openapi: '3.0.2'

info:
  title: "Test API"
  description: "テスト用のAPIです"
  version: '1.0'
servers:
  - url: "https://localhost:8000"
    description: "ローカル"
    
paths:
  /test1:
    get:
      summary: "テスト1"
      tags:
        - "test1"
      deprecated: false
      security:
       - api_key: []
      responses:
        '200':
          description: OK

  /test2:
    get:
      summary: "テスト2"
      tags:
        - "test2"
      deprecated: false
      security:
        - api_key: []
      responses:
        '200':
          description: OK


